### PR TITLE
Fixed Freeplay Icons bugging out the pause menu

### PR DESCRIPTION
**Pull request by Leather128**
Yeah so that happened, and now it's fixed.

### CODE REVIEW

**Comment by rayanmargham** [comment]
you might wanna check it again

**Comment by Leather128** [comment]
you sure? i tried these new commits and they seemed to fix the pause menu bug

**Comment by Leather128** [comment]
wait nvm i think the merge broke something, lemme re-commit my stuffs

**Comment by Leather128** [comment]
ok i think you can merge this now (aka it works)

**Pull request merged**
